select * from customer limit 20
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select *
from customer
where discount_applied = 'Yes' and purchase_amount  >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_count,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT 
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS sub
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_no
    FROM customer
    GROUP BY category, item_purchased
) AS ranked
WHERE rank_no <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
